### ISSUE TITLE
Are these duplicates?

### ISSUE THREAD

**Issue by michaelcsikos** [matthewproctor/australianpostcodes#10]
ALAWA,NT,810
AUSTRALIAN NATIONAL UNIVERSITY,ACT,200
BARTON,ACT,221
BRINKIN,NT,810
CASUARINA,NT,810
COCONUT GROVE,NT,810
DARWIN,NT,800
DARWIN,NT,801
KALGOORLIE,WA,6433
PARAP,NT,804

I also noticed there's a double quote in ABINGDON DOWNS"",QLD,4892

Thanks for your efforts with this project.

**Comment by michaelcsikos** [comment]
My assumption is that the Locality + State + PostCode should form a natural key. Using this rule, there are also the following duplicates:

ACACIA HILLS,NT,822
ADELAIDE RIVER,NT,846
ALI CURUNG,NT,872
ALICE SPRINGS,NT,870
ALICE SPRINGS,NT,871
ALICE SPRINGS,NT,872
ALYANGULA,NT,885
AMATA,NT,872
AMOONGUNA,NT,872
AMOONGUNA,NT,873
ANGURUGU,NT,822
ANNIE RIVER,NT,822
ANULA,NT,812
ARCHER,NT,830
AREYONGA,NT,872
ARUMBERA,NT,873
ATITJERE,NT,872
AVON DOWNS,NT,862
BAGOT,NT,820
BAKEWELL,NT,832
BARROW CREEK,NT,872
BARUNGA,NT,852
BATCHELOR,NT,845
BATHURST ISLAND,NT,822
BAYVIEW,NT,820
BEES CREEK,NT,822
BELLAMACK,NT,832
BERRIMAH,NT,828
BERRY SPRINGS,NT,838
BESWICK,NT,852
BORROLOOLA,NT,854
BRUNCHILLY,NT,861
CANTEEN CREEK,NT,872
CASUARINA,NT,811
CHARLES DARWIN,NT,820
CONNELLAN,NT,873
COOLALINGA,NT,839
COONAWARRA,NT,820
COX PENINSULA,NT,822
CRESSWELL DOWNS,NT,862
CULLEN BAY,NT,820
DALY RIVER,NT,822
DALY WATERS,NT,852
DARWIN DC,NT,820
DARWIN RIVER,NT,841
DELISSAVILLE,NT,822
DRIVER,NT,830
DUNDEE BEACH,NT,840
DUNDEE DOWNS,NT,840
DUNDEE FOREST,NT,840
DURACK,NT,830
EAST POINT,NT,820
ELLIOTT,NT,862
ERLDUNDA,NT,872
FANNIE BAY,NT,820
FARRAR,NT,830
FINKE,NT,872
FLY CREEK,NT,822
FLYNN,NT,875
GALIWINKU,NT,822
GAPUWIYAK,NT,880
GIBSON DESERT NORTH,WA,872
GIBSON DESERT SOUTH,WA,872
GOULBURN ISLAND,NT,822
GOVE,NT,880
GRAY,NT,830
GUNN POINT,NT,822
GUNN,NT,832
HAASTS BLUFF,NT,872
HELEN SPRINGS,NT,862
HERBERT,NT,836
HERMANNSBURG,NT,872
HOWARD SPRINGS,NT,835
HUMPTY DOO,NT,836
ILPARPA,NT,873
IRLPME,NT,874
JABIRU,NT,886
JINGILI,NT,810
KALTUKATJARA,NT,872
KARAMA,NT,812
KATHERINE,NT,850
KATHERINE,NT,851
KATHERINE,NT,852
KILGARIFF,NT,873
KING ASH BAY,NT,854
KINTORE,NT,872
KNUCKEY LAGOON,NT,828
KULGERA,NT,872
LAJAMANU,NT,852
LAKE BENNETT,NT,822
LAMBELLS LAGOON,NT,822
LARAPINTA,NT,875
LARRAKEYAH,NT,820
LARRIMAH,NT,852
LEANYER,NT,812
LEE POINT,NT,810
LIVINGSTONE,NT,822
LUDMILLA,NT,820
MALAK,NT,812
MANBULLOO,NT,852
MANINGRIDA,NT,822
MANTON,NT,837
MARANBOY,NT,852
MARLOW LAGOON,NT,830
MARRARA,NT,812
MATARANKA,NT,852
MCMINNS LAGOON,NT,822
MIDDLE POINT,NT,822
MILINGIMBI,NT,822
MILLNER,NT,810
MIMILI,SA,872
MINJILANG,NT,822
MITCHELL,NT,832
MOIL,NT,810
MOULDEN,NT,830
MOUNT LIEBIG,NT,872
MUCKATY STATION,NT,862
NAKARA,NT,810
NEWCASTLE WATERS,NT,862
NGAANYATJARRA-GILES,WA,872
NGUIU,NT,822
NGUKURR,NT,852
NHULUNBUY,NT,880
NHULUNBUY,NT,881
NIGHTCLIFF,NT,810
NIGHTCLIFF,NT,814
NOONAMAH,NT,837
NUMBULWAR,NT,852
OENPELLI,NT,822
PALMERSTON,NT,830
PALMERSTON,NT,831
PAPUNYA,NT,872
PINE CREEK,NT,847
PINELANDS,NT,829
POINT STEPHENS,NT,822
PULARUMPI,NT,822
RAMINGINING,NT,822
RAPID CREEK,NT,810
RENNER SPRINGS,NT,862
ROSEBERY HEIGHTS,NT,832
ROSEBERY,NT,832
ROSS,NT,873
SANTA TERESA,NT,872
SHOAL BAY,NT,830
SOUTHPORT,NT,822
STUART PARK,NT,820
TENNANT CREEK,NT,860
TENNANT CREEK,NT,861
TENNANT CREEK,NT,862
THE GARDENS,NT,820
THE NARROWS,NT,820
TI TREE,NT,872
TIMBER CREEK,NT,852
TIWI,NT,810
TORTILLA FLATS,NT,822
ULURU,NT,872
UMBAKUMBA,NT,822
UNDOOLYA,NT,874
VIRGINIA,NT,834
VIRGINIA,NT,835
WADEYE,NT,822
WAGAIT BEACH,NT,822
WAGAMAN,NT,810
WALLACE ROCKHOLE,NT,872
WANGURI,NT,810
WARREGO,NT,862
WAVE HILL,NT,852
WEDDELL,NT,822
WILLOWRA,NT,872
WILORA,NT,872
WINNELLIE,NT,820
WINNELLIE,NT,821
WINNELLIE,NT,822
WINNELLIE,NT,906
WINNELLIE,NT,907
WOLLOGORANG STATION,NT,862
WOODROFFE,NT,830
WOOLANING,NT,822
WOOLNER,NT,820
WULAGI,NT,812
YARRAWONGA,NT,830
YIRRKALA,NT,880
YUELAMU,NT,872
YUENDUMU,NT,872
YULARA,NT,872

**Comment by matthewproctor** [comment]
Hi Michael,
Thanks for picking up on those! 
I'll fixing them in the next release (this weekend hopefully).
Cheers,
Matthew
