### ISSUE TITLE
A few more potential changes

### ISSUE THREAD

**Issue by michaelcsikos** [matthewproctor/australianpostcodes#11]
Insert:
AVONSIDE,NSW,2628
LONG PLAIN,NSW,2629
TEXAS,NSW,4385 // This looks weird, but it's right on the border, so both QLD and NSW are correct

Delete:
O'REILLY,QLD,4211

Update (wrong state):
SPEEWA,VIC,3585

**Comment by matthewproctor** [comment]
Thanks heaps for that Michael, will update.
