### ISSUE TITLE
Duplicate Suburb/Postcode

### ISSUE THREAD

**Issue by matthewboler** [matthewproctor/australianpostcodes#12]
Hi Matthew - thanks for providing this file.  In the CSV version I've found that 
0829 | PINELANDS | NT is listed twice (with different source ids).  There may be a good reason for this but it is the only record in the file with duplicate postcode/suburb/state.

Cheers,
Matt

**Comment by matthewproctor** [comment]
Thanks Matt, I've deleted it and it will be updated in the next deploy. (Later today)
