### ISSUE TITLE
3001 lat/long

### ISSUE THREAD

**Issue by pigd0g** [matthewproctor/australianpostcodes#13]
Hey, first of all - great work maintaining this resource!

A minor issue I noted whilst testing, 3001 lat/long should be equal to the same lat/long as 3000 it's the GPO boxes for Melbourne and currently positions way off.  See https://www.australiapostcode.com/vic-melbourne-gpo-boxes.html

Cheers

**Comment by matthewproctor** [comment]
Well spotted, thanks for that. I'll update it.
