### ISSUE TITLE
QLD Locality GREENMOUNT 4225, Uncertain if this is a legitimate location, could be GREENMOUNT BEACH

### ISSUE THREAD

**Issue by jafin** [matthewproctor/australianpostcodes#15]
Locality: GREENMOUNT
Postcode 4225  (Coolangatta)

Is it correctly called GREENMOUNT BEACH ?
https://www.google.com/maps/place/Greenmount+Beach/@-28.1634335,153.5421139,16.37z/data=!4m5!3m4!1s0x6b9100303e44187f:0x9f4f6cf016dca2e9!8m2!3d-28.1639838!4d153.547601

Using Australia Posts's search, there was no result for GREENMOUNT 4225 nor GREENMOUNT BEACH. (But I do see there are quite a few entries in the dataset that do not resolve via the AUS Post lookup so this may be intentional)

![image](https://user-images.githubusercontent.com/127927/88793511-40e74800-d1e0-11ea-8966-6e2aa6220556.png)

Anyhow leave it up to you, I created a PR that renames GREENMOUT (4225) to GREENMOUT BEACH.  Feel free to close/ignore. #16

**Comment by matthewproctor** [comment]
This one is strange, I have found multiple references to both GREENMOUNT and GREENMOUNT BEACH, even on bing/google maps. So I'll add both to be safe.
