### ISSUE TITLE
Postcode & SA3 Association

### ISSUE THREAD

**Issue by MahdiKarimipour** [matthewproctor/australianpostcodes#17]
Is it possible that one postcode could belong to two SA3? 

{

    "id": 16718,
    "postcode": "2826",
    "locality": "BOGAN",
    "state": "NSW",
    "long": 147.4794,
    "lat": -32.0288,
    "dc": "",
    "type": "",
    "status": "Updated 25-Mar-2020 SA3",
    "sa3": "10501",
    "sa3name": "Bourke - Cobar - Coonamble",
    "sa4": "105",
    "sa4name": "Far West and Orana",
    "region": "R3"

},
{

    "id": 16719,
    "postcode": "2826",
    "locality": "NEVERTIRE",
    "state": "NSW",
    "long": 147.6555,
    "lat": -31.8559,
    "dc": "",
    "type": "",
    "status": "Updated 25-Mar-2020 SA3",
    "sa3": "10503",
    "sa3name": "Dubbo",
    "sa4": "105",
    "sa4name": "Far West and Orana",
    "region": "R3"

},

**Comment by matthewproctor** [comment]
Yeah, there's a couple of those, I just let the code pick the first SA region.  I may include multiples in the next update.
