### ISSUE TITLE
Question about North Sydney NSW

### ISSUE THREAD

**Issue by simonstassen** [matthewproctor/australianpostcodes#20]
Thanks heaps for this great resource. 

Just trying to find out more about where the data for North Sydney post codes 4327 and 4330 comes from?

**Comment by simonstassen** [comment]
Also, Murray Downs post code 3585

**Comment by simonstassen** [comment]
It looks like 4327 was the id for North Sydney 2055 before the November 2020 update. In the November 2020 the id became a post code.

**Comment by matthewproctor** [comment]
Hi Simon, yeah I messed up a sql query when updating it. Fixing now, will update later tonight.
