### ISSUE TITLE
lat/lon_precise is string

### ISSUE THREAD

**Issue by etjernst** [matthewproctor/australianpostcodes#21]
Maybe there is some reason for this, but for some reason the [json](https://www.matthewproctor.com/Content/postcodes/australian_postcodes.json) has lat/long as values & the ones from google maps are strings. Minor inconvenience but thought I'd flag it.

```
long:   149.119
lat:  -35.2777
...
Lat_precise:  "-35.2777"
Long_precise:  "149.119"
```

**Comment by matthewproctor** [comment]
It's just the way I'm exporting it - my source is a CSV file (which is untyped), then exporting it to JSON
