### ISSUE TITLE
Derrimut Postcode

### ISSUE THREAD

**Issue by PeterOwenGithub** [matthewproctor/australianpostcodes#23]
Derrimut postcode was changed in August 2018 from 3030 to 3026, assume this should be reflected in the data but isn't yet

https://brimbanknorthwest.starweekly.com.au/news/derrimut-moves-to-new-post-code/
https://auspost.com.au/postcode/derrimut

**Comment by matthewproctor** [comment]
Thanks Peter, I've updated it and it will be included in the next release (later tonight)
