### ISSUE TITLE
Added your repo to the awesome-aussie list

### ISSUE THREAD

**Issue by DiemenDesign** [matthewproctor/australianpostcodes#26]
Hi Matthew, I just wanted to let you know that I've added a link to this repository to this https://github.com/DiemenDesign/awesome-aussie/blob/main/README.md repository, so you can suggest edits, add other repos, or request your link be removed.

**Comment by matthewproctor** [comment]
Thanks Diemen, that's a great listing! I've linked back on the web site. I'll have a think about others to suggest. 👍
