### ISSUE TITLE
Misclassified localities

### ISSUE THREAD

**Issue by edschofield** [matthewproctor/australianpostcodes#27]
Thanks for this awesome repo! Very useful.

I have visualised each postcode as a scatter plot using Plotly / Mapbox and this shows immediately that a few localities have dodgy data in the Google / precise coordinates columns. See the HTML plot in the zip file attached.

The dodgy ones I can see are:

- Tarrawarra QLD (coordinates are for Tarrawarra VIC) but should be a suburb of Cairns
- Diamond Head QLD coordinates place it firmly in NSW
- Martins Creek, Minto, and Yarrunga (all VIC) have coordinates placing them in NSW
- Coordinates for postcode 0872 ("ANANGU PITJANTJATJARA YANKUNYTJATJARA") also appear to be firmly in NT whereas the data describes it as being in SA
- Berrambool VIC mixes up its "precise coordinates" and data with Berrambool NSW
- Deakin University 3217 (record 6684): it seems this is referring to the campus in Geelong (Waurn Ponds) but the SA and Google Maps data has found the Burwood campus.
- Happy Valley QLD 4655: seems this is a minor area sharing Hervey Bay's postcode but data was for Happy Valley 4825 near Mount Isa
- Happy Valley 2430 has coordinates in SA
- Christies VIC 3920 has coordinates in SA

In all of these cases the places don't appear in Australia Post's postcode database or Google Maps but they do appear on http://postcodes-australia.com. (They seem to be minor suburbs that share a postcode with others.)

Not sure of your workflow for contributions. I'd be happy to fix them in the CSV and make a pull request but the repo has so many file formats it would be far more work to fix them all. I assume you have some automated process to generate the different file formats from one canonical source? 

[visualisation.zip](https://github.com/matthewproctor/australianpostcodes/files/7384721/visualisation.zip)

**Comment by matthewproctor** [comment]
Thanks Ed, much appreciated. Will update.
