### ISSUE TITLE
Postcodes are wrong

### ISSUE THREAD

**Issue by TerryJey** [matthewproctor/australianpostcodes#4]
A number of postcodes are wrong. Some examples:

ENMORE NSW is 2358 but should be 2042
ELDERSLIE NSW is 2570 but should be 2335

**Comment by matthewproctor** [comment]
Hi Terry,
I've fixed Enmore.
Aus Post show Elderslie as being in both postcodes (2570 and 2335) so I'll leave that for now.
https://auspost.com.au/postcode/2335
https://auspost.com.au/postcode/2570
