### ISSUE TITLE
This file might help fill some gaps

### ISSUE THREAD

**Issue by Stuartpj** [matthewproctor/australianpostcodes#5]
Hi, attached excel file from a transport company might help fill some gaps

[Australian Postcode to Delivery Zone.xlsx](https://github.com/matthewproctor/australianpostcodes/files/3370574/Australian.Postcode.to.Delivery.Zone.xlsx)

**Comment by matthewproctor** [comment]
Thanks Stuart, that's fantastic. It fills in quite a few gaps - much appreciated!
